import type { Exercise } from '@/types';

export const EXERCISES: Exercise[] = [
  // PECHO
  {
    id: 'press-banca-plano',
    name: 'Press Banca Plano',
    muscleGroup: 'pecho',
    description: 'Ejercicio fundamental para el desarrollo del pecho. Trabaja pectoral mayor, deltoides anterior y tríceps.',
    steps: [
      'Acostarse en el banco plano con los pies firmes en el suelo',
      'Agarrar la barra con un agarre ligeramente más ancho que los hombros',
      'Bajar la barra controladamente hasta tocar el pecho medio',
      'Empujar la barra hacia arriba hasta extender los brazos sin bloquear los codos',
      'Mantener los omóplatos retraídos durante todo el movimiento',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'aperturas-inclinadas',
    name: 'Aperturas Inclinadas',
    muscleGroup: 'pecho',
    description: 'Ejercicio de aislamiento para la parte superior del pecho con mancuernas.',
    steps: [
      'Sentarse en un banco inclinado a 30-45 grados',
      'Sostener las mancuernas con los brazos extendidos sobre el pecho',
      'Abrir los brazos en arco bajando las mancuernas a los lados',
      'Mantener una ligera flexión en los codos durante todo el recorrido',
      'Volver a la posición inicial apretando el pecho',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'press-inclinado',
    name: 'Press Inclinado con Mancuernas',
    muscleGroup: 'pecho',
    description: 'Variante del press banca que enfatiza la parte superior del pecho.',
    steps: [
      'Ajustar el banco a 30-45 grados de inclinación',
      'Sostener una mancuerna en cada mano a la altura del pecho',
      'Empujar las mancuernas hacia arriba y ligeramente hacia adentro',
      'Bajar controladamente hasta que los codos estén a 90 grados',
      'Mantener los pies firmes en el suelo',
    ],
    videoUrl: 'SEARCH',
  },
  // ESPALDA
  {
    id: 'jalon-polea-alta',
    name: 'Jalón Polea Alta',
    muscleGroup: 'espalda',
    description: 'Ejercicio clave para el desarrollo del dorsal ancho y la amplitud de la espalda.',
    steps: [
      'Sentarse en la máquina con las piernas aseguradas',
      'Agarrar la barra con agarre ancho, palmas mirando hacia adelante',
      'Tirar la barra hacia abajo hasta la parte superior del pecho',
      'Apretar los omóplatos al final del movimiento',
      'Volver arriba controladamente sin soltar completamente la tensión',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'remo-con-barra',
    name: 'Remo con Barra',
    muscleGroup: 'espalda',
    description: 'Ejercicio compuesto para el grosor de la espalda.',
    steps: [
      'De pie, inclinar el torso a 45 grados con las rodillas ligeramente flexionadas',
      'Agarrar la barra con agarre prono a la anchura de los hombros',
      'Tirar la barra hacia el abdomen bajo',
      'Apretar los omóplatos al final del movimiento',
      'Bajar controladamente manteniendo la postura',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'remo-mancuerna',
    name: 'Remo con Mancuerna',
    muscleGroup: 'espalda',
    description: 'Ejercicio unilateral para trabajar cada lado de la espalda independientemente.',
    steps: [
      'Apoyar una rodilla y una mano en el banco',
      'Con la otra mano sostener la mancuerna con el brazo extendido',
      'Tirar la mancuerna hacia la cadera manteniendo el codo cerca del cuerpo',
      'Apretar el dorsal en la parte alta del movimiento',
      'Bajar controladamente y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  // HOMBROS
  {
    id: 'press-hombros',
    name: 'Press de Hombros',
    muscleGroup: 'hombros',
    description: 'Ejercicio principal para el desarrollo de los deltoides.',
    steps: [
      'Sentarse con la espalda apoyada en el banco vertical',
      'Sostener las mancuernas a la altura de los hombros',
      'Empujar hacia arriba hasta casi extender los brazos',
      'Bajar controladamente hasta la posición inicial',
      'No bloquear los codos en la extensión',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'elevaciones-laterales',
    name: 'Elevaciones Laterales',
    muscleGroup: 'hombros',
    description: 'Ejercicio de aislamiento para el deltoides lateral.',
    steps: [
      'De pie con una mancuerna en cada mano a los lados',
      'Elevar los brazos hacia los lados hasta la altura de los hombros',
      'Mantener una ligera flexión en los codos',
      'Bajar controladamente sin dejar caer el peso',
      'Evitar usar impulso del cuerpo',
    ],
    videoUrl: 'SEARCH',
  },
  // BICEPS
  {
    id: 'curl-biceps-barra',
    name: 'Curl Bíceps con Barra',
    muscleGroup: 'biceps',
    description: 'Ejercicio clásico para el desarrollo del bíceps.',
    steps: [
      'De pie con la barra a la anchura de los hombros',
      'Flexionar los codos llevando la barra hacia los hombros',
      'Mantener los codos pegados al cuerpo durante todo el movimiento',
      'Bajar controladamente sin extender completamente los codos',
      'No balancear el cuerpo para subir el peso',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'curl-martillo',
    name: 'Curl Martillo',
    muscleGroup: 'biceps',
    description: 'Variante del curl que trabaja bíceps y braquial.',
    steps: [
      'De pie con mancuernas a los lados, palmas mirando hacia el cuerpo',
      'Flexionar los codos sin rotar las muñecas',
      'Subir las mancuernas hasta la altura de los hombros',
      'Mantener los codos fijos a los lados',
      'Bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  // TRICEPS
  {
    id: 'extension-triceps-polea',
    name: 'Extensión de Tríceps en Polea',
    muscleGroup: 'triceps',
    description: 'Ejercicio de aislamiento para los tres cabezas del tríceps.',
    steps: [
      'De pie frente a la polea alta con agarre de cuerda o barra',
      'Mantener los codos pegados al cuerpo a 90 grados',
      'Extender los brazos hacia abajo completamente',
      'Apretar los tríceps en la extensión completa',
      'Volver controladamente a 90 grados',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'fondos-triceps',
    name: 'Fondos de Tríceps',
    muscleGroup: 'triceps',
    description: 'Ejercicio con peso corporal para tríceps.',
    steps: [
      'Apoyar las manos en un banco detrás del cuerpo',
      'Extender las piernas hacia adelante',
      'Flexionar los codos bajando el cuerpo',
      'Bajar hasta que los codos formen 90 grados',
      'Empujar hacia arriba extendiendo los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  // PIERNAS
  {
    id: 'sentadilla',
    name: 'Sentadilla con Barra',
    muscleGroup: 'piernas',
    description: 'El rey de los ejercicios. Trabaja cuádriceps, glúteos, isquiotibiales y core.',
    steps: [
      'Colocar la barra sobre los trapecios, no sobre el cuello',
      'Pies a la anchura de los hombros, puntas ligeramente hacia afuera',
      'Bajar como si te sentaras en una silla',
      'Mantener las rodillas en línea con las puntas de los pies',
      'Bajar hasta que los muslos estén paralelos al suelo o más abajo',
      'Subir empujando con los talones',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'peso-muerto',
    name: 'Peso Muerto',
    muscleGroup: 'piernas',
    description: 'Ejercicio compuesto que trabaja toda la cadena posterior.',
    steps: [
      'De pie con los pies a la anchura de las caderas',
      'Agarrar la barra con agarre mixto o doble prono',
      'Mantener la espalda recta y el pecho arriba',
      'Levantar la barra extendiendo caderas y rodillas simultáneamente',
      'Mantener la barra cerca del cuerpo durante todo el recorrido',
      'Bajar controladamente manteniendo la espalda recta',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'prensa-piernas',
    name: 'Prensa de Piernas',
    muscleGroup: 'piernas',
    description: 'Ejercicio de máquina para cuádriceps y glúteos.',
    steps: [
      'Sentarse en la máquina con la espalda bien apoyada',
      'Colocar los pies a la anchura de los hombros en la plataforma',
      'Soltar los seguros y bajar la plataforma flexionando las rodillas',
      'Bajar hasta que las rodillas formen 90 grados',
      'Empujar hacia arriba sin bloquear las rodillas',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'zancadas',
    name: 'Zancadas',
    muscleGroup: 'piernas',
    description: 'Ejercicio unilateral para cuádriceps y glúteos.',
    steps: [
      'De pie con mancuernas a los lados o barra en los hombros',
      'Dar un paso largo hacia adelante',
      'Flexionar ambas rodillas bajando la trasera hacia el suelo',
      'La rodilla delantera no debe pasar la punta del pie',
      'Empujar con el pie delantero para volver a la posición inicial',
    ],
    videoUrl: 'SEARCH',
  },
  // ABDOMEN
  {
    id: 'plancha',
    name: 'Plancha',
    muscleGroup: 'abdomen',
    description: 'Ejercicio isométrico para fortalecer todo el core.',
    steps: [
      'Apoyar los antebrazos y las puntas de los pies en el suelo',
      'Mantener el cuerpo en línea recta de cabeza a pies',
      'Apretar el abdomen y los glúteos',
      'No dejar caer las caderas ni subirlas demasiado',
      'Mantener la posición el tiempo indicado',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'crunch-polea',
    name: 'Crunch en Polea',
    muscleGroup: 'abdomen',
    description: 'Ejercicio con resistencia para el recto abdominal.',
    steps: [
      'Arrodillarse frente a la polea alta con la cuerda',
      'Sostener la cuerda a los lados de la cabeza',
      'Flexionar el torso hacia abajo contrayendo el abdomen',
      'No tirar con los brazos, el movimiento es del core',
      'Volver controladamente a la posición inicial',
    ],
    videoUrl: 'SEARCH',
  },
  // PECHO (extras para enfasis)
  {
    id: 'press-declinado',
    name: 'Press Declinado con Barra',
    muscleGroup: 'pecho',
    description: 'Enfatiza la parte inferior del pectoral. Basado en ACSM para desarrollo completo del pecho.',
    steps: [
      'Acostarse en banco declinado (-15 grados) con pies asegurados',
      'Agarrar la barra ligeramente mas ancho que los hombros',
      'Bajar la barra al pecho bajo de forma controlada',
      'Empujar hacia arriba hasta extender los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'cruces-polea',
    name: 'Cruces en Polea',
    muscleGroup: 'pecho',
    description: 'Aislamiento del pectoral con tension constante. Ideal para volumen y definicion.',
    steps: [
      'De pie entre las poleas altas con un pie adelante',
      'Agarrar las manijas con los brazos abiertos',
      'Llevar las manos hacia el centro apretando el pecho',
      'Volver controladamente manteniendo tension',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'flexiones',
    name: 'Flexiones de Brazos',
    muscleGroup: 'pecho',
    description: 'Ejercicio con peso corporal para pecho, hombros y triceps.',
    steps: [
      'Manos en el suelo a la anchura de los hombros',
      'Cuerpo recto de cabeza a pies, core activado',
      'Bajar el pecho hasta casi tocar el suelo',
      'Empujar hacia arriba hasta extender los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  // ESPALDA (extras para enfasis)
  {
    id: 'dominadas',
    name: 'Dominadas',
    muscleGroup: 'espalda',
    description: 'Ejercicio con peso corporal para dorsales. Referencia NSCA para fuerza de traccion.',
    steps: [
      'Colgarse de la barra con agarre prono mas ancho que los hombros',
      'Tirar del cuerpo hacia arriba hasta pasar la barbilla de la barra',
      'Bajar controladamente sin dejarse caer',
      'Mantener el core activado durante todo el movimiento',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'pullover',
    name: 'Pullover con Mancuerna',
    muscleGroup: 'espalda',
    description: 'Trabaja dorsales y serrato. Ejercicio clasico para amplitud de espalda.',
    steps: [
      'Acostarse en el banco con solo los hombros apoyados',
      'Sostener una mancuerna con ambas manos sobre el pecho',
      'Bajar la mancuerna detras de la cabeza con los brazos semi-extendidos',
      'Volver a la posicion inicial apretando dorsales',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'remo-polea-baja',
    name: 'Remo en Polea Baja',
    muscleGroup: 'espalda',
    description: 'Ejercicio para grosor de espalda con tension constante.',
    steps: [
      'Sentarse con los pies en la plataforma y rodillas ligeramente flexionadas',
      'Agarrar la manija V con ambas manos',
      'Tirar hacia el abdomen apretando los omoplatos',
      'Volver controladamente estirando los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  // HOMBROS (extras para enfasis)
  {
    id: 'face-pull',
    name: 'Face Pull',
    muscleGroup: 'hombros',
    description: 'Ejercicio para deltoides posterior y salud del hombro. Recomendado por ACSM para prevencion de lesiones.',
    steps: [
      'De pie frente a la polea alta con cuerda',
      'Tirar la cuerda hacia la cara separando las manos',
      'Rotar los hombros hacia atras apretando los omoplatos',
      'Volver controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'press-arnold',
    name: 'Press Arnold',
    muscleGroup: 'hombros',
    description: 'Variante del press que trabaja las tres cabezas del deltoides con rotacion.',
    steps: [
      'Sentado con mancuernas frente al pecho, palmas hacia vos',
      'Rotar las mancuernas mientras las empujas hacia arriba',
      'Terminar con las palmas mirando hacia adelante arriba',
      'Bajar rotando de vuelta a la posicion inicial',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'elevaciones-frontales',
    name: 'Elevaciones Frontales',
    muscleGroup: 'hombros',
    description: 'Aislamiento del deltoides anterior.',
    steps: [
      'De pie con mancuernas frente a los muslos',
      'Elevar un brazo al frente hasta la altura de los hombros',
      'Bajar controladamente y alternar con el otro brazo',
      'No usar impulso del cuerpo',
    ],
    videoUrl: 'SEARCH',
  },
  // BICEPS (extras para enfasis)
  {
    id: 'curl-concentrado',
    name: 'Curl Concentrado',
    muscleGroup: 'biceps',
    description: 'Aislamiento maximo del biceps. Elimina trampa de impulso.',
    steps: [
      'Sentado, apoyar el codo en la cara interna del muslo',
      'Con mancuerna, flexionar el brazo concentrando en el biceps',
      'Apretar arriba por 1 segundo',
      'Bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'curl-scott',
    name: 'Curl en Banco Scott',
    muscleGroup: 'biceps',
    description: 'Curl con soporte que aisla el biceps y previene trampa.',
    steps: [
      'Sentarse en el banco Scott con los brazos sobre la almohadilla',
      'Agarrar la barra o mancuernas con agarre supino',
      'Flexionar los codos subiendo el peso',
      'Bajar controladamente sin extender completamente',
    ],
    videoUrl: 'SEARCH',
  },
  // TRICEPS (extras para enfasis)
  {
    id: 'press-frances',
    name: 'Press Frances',
    muscleGroup: 'triceps',
    description: 'Ejercicio compuesto para las tres cabezas del triceps. Basado en NSCA.',
    steps: [
      'Acostado en banco plano con barra o mancuernas sobre el pecho',
      'Flexionar los codos bajando el peso hacia la frente',
      'Mantener los codos apuntando al techo, no abrirlos',
      'Extender los brazos volviendo a la posicion inicial',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'kickback-triceps',
    name: 'Kickback de Triceps',
    muscleGroup: 'triceps',
    description: 'Aislamiento del triceps con mancuerna.',
    steps: [
      'Inclinar el torso a 90 grados, un brazo apoyado en el banco',
      'Codo a 90 grados pegado al cuerpo',
      'Extender el brazo hacia atras apretando el triceps',
      'Volver a 90 grados controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  // PIERNAS (extras para enfasis)
  {
    id: 'extension-cuadriceps',
    name: 'Extension de Cuadriceps',
    muscleGroup: 'piernas',
    description: 'Aislamiento del cuadriceps en maquina.',
    steps: [
      'Sentarse en la maquina con la espalda apoyada',
      'Colocar los pies detras del rodillo',
      'Extender las piernas hasta la extension completa',
      'Apretar el cuadriceps arriba por 1 segundo',
      'Bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'curl-femoral',
    name: 'Curl Femoral',
    muscleGroup: 'piernas',
    description: 'Aislamiento de isquiotibiales en maquina.',
    steps: [
      'Acostarse boca abajo en la maquina',
      'Colocar los tobillos debajo del rodillo',
      'Flexionar las rodillas llevando los talones hacia los gluteos',
      'Apretar arriba por 1 segundo',
      'Bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    muscleGroup: 'piernas',
    description: 'Ejercicio principal para gluteos. Referencia NSCA para activacion glutea maxima.',
    steps: [
      'Sentarse en el suelo con la espalda alta apoyada en un banco',
      'Colocar la barra sobre las caderas con proteccion',
      'Empujar las caderas hacia arriba apretando los gluteos',
      'Mantener arriba 1 segundo',
      'Bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'sentadilla-bulgara',
    name: 'Sentadilla Bulgara',
    muscleGroup: 'piernas',
    description: 'Ejercicio unilateral avanzado para cuadriceps y gluteos.',
    steps: [
      'De pie con un pie apoyado en un banco detras',
      'Bajar flexionando la rodilla delantera',
      'Mantener el torso erguido',
      'Bajar hasta que el muslo delantero este paralelo al suelo',
      'Subir empujando con el talon delantero',
    ],
    videoUrl: 'SEARCH',
  },
  // ABDOMEN (extras para enfasis)
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    muscleGroup: 'abdomen',
    description: 'Ejercicio dinamico para core y cardio simultaneo.',
    steps: [
      'Posicion de flexion con brazos extendidos',
      'Llevar una rodilla al pecho rapidamente',
      'Alternar las piernas de forma rapida y controlada',
      'Mantener las caderas bajas y el core activado',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'elevacion-piernas',
    name: 'Elevacion de Piernas Colgado',
    muscleGroup: 'abdomen',
    description: 'Ejercicio avanzado para abdomen inferior. Alta activacion segun ACSM.',
    steps: [
      'Colgarse de una barra con agarre prono',
      'Elevar las piernas rectas hasta 90 grados',
      'Bajar controladamente sin balancear',
      'Para principiantes: elevar las rodillas al pecho',
    ],
    videoUrl: 'SEARCH',
  },
  // PECHO (casa - sin maquinas)
  {
    id: 'flexiones-diamante',
    name: 'Flexiones Diamante',
    muscleGroup: 'pecho',
    description: 'Flexiones con manos juntas formando un diamante. Enfatiza triceps y pecho interno.',
    steps: [
      'Manos juntas en el suelo formando un diamante con pulgares e indices',
      'Cuerpo recto, core activado',
      'Bajar el pecho hasta las manos',
      'Empujar hacia arriba hasta extender los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'flexiones-declinadas',
    name: 'Flexiones Declinadas',
    muscleGroup: 'pecho',
    description: 'Flexiones con pies elevados para mayor enfasis en pecho superior.',
    steps: [
      'Colocar los pies sobre una silla o banco',
      'Manos en el suelo a la anchura de los hombros',
      'Bajar el pecho al suelo manteniendo el core firme',
      'Empujar hacia arriba hasta extender los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'flexiones-abiertas',
    name: 'Flexiones Abiertas',
    muscleGroup: 'pecho',
    description: 'Flexiones con agarre ancho para mayor activacion del pectoral.',
    steps: [
      'Manos mas anchas que los hombros en el suelo',
      'Cuerpo recto de cabeza a pies',
      'Bajar el pecho al suelo controladamente',
      'Empujar hacia arriba apretando el pecho',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'dips-silla',
    name: 'Fondos entre Sillas',
    muscleGroup: 'pecho',
    description: 'Fondos usando dos sillas para trabajar pecho y triceps sin equipamiento.',
    steps: [
      'Colocar dos sillas resistentes separadas al ancho de los hombros',
      'Apoyar una mano en cada silla, cuerpo suspendido',
      'Bajar flexionando los codos hasta 90 grados',
      'Empujar hacia arriba hasta extender los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  // ESPALDA (casa - sin maquinas)
  {
    id: 'remo-invertido',
    name: 'Remo Invertido',
    muscleGroup: 'espalda',
    description: 'Remo con peso corporal usando una mesa o barra baja.',
    steps: [
      'Acostarse debajo de una mesa resistente o barra baja',
      'Agarrar el borde con agarre prono, cuerpo recto',
      'Tirar del pecho hacia la mesa apretando omoplatos',
      'Bajar controladamente sin tocar el suelo',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'superman',
    name: 'Superman',
    muscleGroup: 'espalda',
    description: 'Ejercicio en suelo para fortalecer la cadena posterior sin equipamiento.',
    steps: [
      'Acostarse boca abajo con brazos extendidos al frente',
      'Elevar simultaneamente brazos y piernas del suelo',
      'Mantener la posicion 2-3 segundos apretando la espalda',
      'Bajar controladamente al suelo',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'superman-alterno',
    name: 'Superman Alterno',
    muscleGroup: 'espalda',
    description: 'Variante del superman elevando un brazo y pierna opuesta alternando.',
    steps: [
      'Acostarse boca abajo con brazos extendidos',
      'Elevar brazo derecho y pierna izquierda simultaneamente',
      'Mantener 2 segundos',
      'Bajar y repetir con el otro lado',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'remo-toalla',
    name: 'Remo con Toalla',
    muscleGroup: 'espalda',
    description: 'Remo isometrico usando una toalla enganchada en una puerta.',
    steps: [
      'Pasar una toalla por una manija de puerta cerrada',
      'Agarrar ambos extremos e inclinar el cuerpo hacia atras',
      'Tirar del cuerpo hacia la puerta apretando la espalda',
      'Volver controladamente a la posicion inclinada',
    ],
    videoUrl: 'SEARCH',
  },
  // HOMBROS (casa - sin maquinas)
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    muscleGroup: 'hombros',
    description: 'Flexion en V invertida para enfatizar los hombros sin equipamiento.',
    steps: [
      'Posicion de flexion con caderas elevadas formando una V invertida',
      'Manos a la anchura de los hombros',
      'Bajar la cabeza hacia el suelo flexionando los codos',
      'Empujar hacia arriba hasta la posicion inicial',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'plancha-lateral-con-elevacion',
    name: 'Plancha Lateral con Elevacion',
    muscleGroup: 'hombros',
    description: 'Plancha lateral elevando el brazo libre para trabajar deltoides.',
    steps: [
      'Posicion de plancha lateral apoyado en un antebrazo',
      'Elevar el brazo libre hacia el techo',
      'Mantener 2 segundos arriba',
      'Bajar controladamente y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'handstand-wall',
    name: 'Handstand en Pared',
    muscleGroup: 'hombros',
    description: 'Apoyo de manos contra la pared para fuerza de hombros.',
    steps: [
      'De espaldas a la pared, colocar las manos en el suelo',
      'Subir los pies por la pared hasta quedar invertido',
      'Mantener la posicion con brazos extendidos y core firme',
      'Bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  // BICEPS (casa)
  {
    id: 'curl-mochila',
    name: 'Curl con Mochila',
    muscleGroup: 'biceps',
    description: 'Curl de biceps usando una mochila cargada con peso.',
    steps: [
      'Cargar una mochila con libros o botellas de agua',
      'Agarrar la mochila por la manija con una mano',
      'Flexionar el codo subiendo la mochila hacia el hombro',
      'Bajar controladamente y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'chin-up',
    name: 'Dominadas Supino',
    muscleGroup: 'biceps',
    description: 'Dominada con agarre supino para mayor enfasis en biceps.',
    steps: [
      'Colgarse de la barra con agarre supino al ancho de los hombros',
      'Tirar del cuerpo hacia arriba pasando la barbilla de la barra',
      'Bajar controladamente',
      'Mantener el core activado durante todo el movimiento',
    ],
    videoUrl: 'SEARCH',
  },
  // TRICEPS (casa)
  {
    id: 'fondos-triceps-suelo',
    name: 'Fondos de Triceps en Silla',
    muscleGroup: 'triceps',
    description: 'Fondos de triceps usando una silla, ideal para entrenar en casa.',
    steps: [
      'Apoyar las manos en el borde de una silla resistente detras del cuerpo',
      'Piernas extendidas al frente',
      'Flexionar los codos bajando el cuerpo',
      'Empujar hacia arriba hasta extender los brazos',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'flexiones-triceps',
    name: 'Flexiones de Triceps',
    muscleGroup: 'triceps',
    description: 'Flexiones con codos pegados al cuerpo para enfatizar triceps.',
    steps: [
      'Posicion de flexion con manos debajo de los hombros',
      'Mantener los codos pegados al cuerpo',
      'Bajar el pecho al suelo controladamente',
      'Empujar hacia arriba manteniendo los codos cerca del torso',
    ],
    videoUrl: 'SEARCH',
  },
  // PIERNAS (casa - sin maquinas)
  {
    id: 'sentadilla-cuerpo',
    name: 'Sentadilla sin Peso',
    muscleGroup: 'piernas',
    description: 'Sentadilla con peso corporal, base de todo entrenamiento de piernas en casa.',
    steps: [
      'De pie con los pies al ancho de los hombros',
      'Bajar como si te sentaras en una silla',
      'Mantener las rodillas alineadas con los pies',
      'Subir empujando con los talones',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'sentadilla-sumo',
    name: 'Sentadilla Sumo',
    muscleGroup: 'piernas',
    description: 'Sentadilla con piernas abiertas para enfatizar aductores y gluteos.',
    steps: [
      'De pie con los pies mucho mas ancho que los hombros, puntas hacia afuera',
      'Bajar manteniendo la espalda recta y el pecho arriba',
      'Bajar hasta que los muslos esten paralelos al suelo',
      'Subir apretando gluteos y aductores',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    muscleGroup: 'piernas',
    description: 'Subida a banco o escalon para cuadriceps y gluteos.',
    steps: [
      'De pie frente a un banco o escalon resistente',
      'Subir con un pie empujando con el talon',
      'Extender la pierna completamente arriba',
      'Bajar controladamente con la misma pierna',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'puente-gluteo',
    name: 'Puente de Gluteo',
    muscleGroup: 'piernas',
    description: 'Ejercicio para gluteos sin equipamiento.',
    steps: [
      'Acostarse boca arriba con rodillas flexionadas y pies en el suelo',
      'Empujar las caderas hacia arriba apretando los gluteos',
      'Mantener arriba 2 segundos',
      'Bajar controladamente sin tocar el suelo',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'puente-gluteo-unilateral',
    name: 'Puente de Gluteo a Una Pierna',
    muscleGroup: 'piernas',
    description: 'Version unilateral del puente para mayor intensidad.',
    steps: [
      'Acostarse boca arriba, una pierna extendida al aire',
      'Empujar la cadera hacia arriba con una sola pierna',
      'Apretar el gluteo arriba por 2 segundos',
      'Bajar controladamente y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'pistol-squat',
    name: 'Sentadilla Pistol',
    muscleGroup: 'piernas',
    description: 'Sentadilla a una pierna. Ejercicio avanzado de fuerza y equilibrio.',
    steps: [
      'De pie sobre una pierna, la otra extendida al frente',
      'Bajar controladamente hasta abajo en una pierna',
      'Mantener la otra pierna extendida sin tocar el suelo',
      'Subir empujando con el talon',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'wall-sit',
    name: 'Sentadilla en Pared',
    muscleGroup: 'piernas',
    description: 'Ejercicio isometrico contra la pared para cuadriceps.',
    steps: [
      'Apoyar la espalda contra la pared',
      'Bajar hasta que los muslos esten paralelos al suelo',
      'Mantener la posicion el tiempo indicado',
      'Las rodillas a 90 grados, no deben pasar los pies',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'elevacion-pantorrillas',
    name: 'Elevacion de Pantorrillas',
    muscleGroup: 'piernas',
    description: 'Ejercicio para pantorrillas que se puede hacer en un escalon.',
    steps: [
      'De pie en el borde de un escalon con los talones al aire',
      'Subir en puntas de pie apretando las pantorrillas',
      'Mantener arriba 1-2 segundos',
      'Bajar controladamente estirando las pantorrillas',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'zancadas-atras',
    name: 'Zancadas Inversas',
    muscleGroup: 'piernas',
    description: 'Zancadas hacia atras, mas amigables con las rodillas.',
    steps: [
      'De pie con los pies juntos',
      'Dar un paso largo hacia atras',
      'Bajar la rodilla trasera hacia el suelo',
      'Empujar con el pie delantero para volver a la posicion inicial',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'zancadas-laterales',
    name: 'Zancadas Laterales',
    muscleGroup: 'piernas',
    description: 'Zancadas hacia el costado para trabajar aductores y abductores.',
    steps: [
      'De pie con los pies juntos',
      'Dar un paso amplio hacia un costado',
      'Flexionar la rodilla de ese lado manteniendo la otra pierna recta',
      'Empujar para volver al centro y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  // PIERNAS / GLUTEOS — nuevos ejercicios
  {
    id: 'patada-gluteo',
    name: 'Patada de Glúteo (Hip Extension)',
    muscleGroup: 'piernas',
    description: 'Ejercicio de aislamiento para glúteos. Extensión de cadera en banco o máquina.',
    steps: [
      'Apoyar el torso sobre un banco con las caderas en el borde',
      'Mantener una pierna apoyada y la otra extendida hacia atrás',
      'Elevar la pierna libre extendiendo la cadera y apretando el glúteo',
      'Bajar controladamente sin tocar el suelo',
      'Completar las repeticiones y cambiar de pierna',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'extension-cadera-polea',
    name: 'Extensión de Cadera en Polea',
    muscleGroup: 'piernas',
    description: 'Aislamiento de glúteos usando la polea baja. Excelente para activación y definición.',
    steps: [
      'Colocar la tobillera en la polea baja',
      'Pararse de frente a la máquina sujetándose con las manos',
      'Llevar la pierna hacia atrás extendiendo la cadera',
      'Apretar el glúteo arriba y mantener 1 segundo',
      'Volver controladamente y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'abduccion-cadera',
    name: 'Abducción de Cadera (Máquina)',
    muscleGroup: 'piernas',
    description: 'Ejercicio en máquina para glúteo medio y menor. Abre las piernas contra resistencia.',
    steps: [
      'Sentarse en la máquina con la espalda apoyada',
      'Colocar las piernas en las almohadillas laterales',
      'Abrir las piernas empujando hacia afuera contra la resistencia',
      'Mantener 1 segundo en la posición abierta apretando los glúteos',
      'Volver controladamente a la posición inicial',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'aduccion-cadera',
    name: 'Aducción de Cadera (Máquina)',
    muscleGroup: 'piernas',
    description: 'Ejercicio en máquina para aductores (parte interna del muslo).',
    steps: [
      'Sentarse en la máquina con la espalda apoyada',
      'Colocar las piernas en las almohadillas laterales (abiertas)',
      'Cerrar las piernas empujando hacia adentro contra la resistencia',
      'Mantener 1 segundo en la posición cerrada',
      'Abrir controladamente a la posición inicial',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'aduccion-cable',
    name: 'Aducción de Cadera en Polea',
    muscleGroup: 'piernas',
    description: 'Trabajo de aductores con polea baja. Permite mayor rango de movimiento que la máquina.',
    steps: [
      'Colocar la tobillera en la polea baja en la pierna más alejada',
      'Pararse de costado a la máquina',
      'Cruzar la pierna por delante del cuerpo contra la resistencia',
      'Controlar el regreso a la posición inicial',
      'Completar las repeticiones y cambiar de lado',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'donkey-kicks',
    name: 'Donkey Kicks',
    muscleGroup: 'piernas',
    description: 'Ejercicio en cuadrupedia para activación de glúteos. Ideal para calentamiento o trabajo sin equipamiento.',
    steps: [
      'Ponerse en cuadrupedia (manos y rodillas en el suelo)',
      'Mantener la espalda recta y el abdomen contraído',
      'Elevar una pierna flexionada hacia el techo empujando con el talón',
      'Apretar el glúteo arriba y mantener 1 segundo',
      'Bajar controladamente sin apoyar la rodilla y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'fire-hydrants',
    name: 'Fire Hydrants',
    muscleGroup: 'piernas',
    description: 'Ejercicio en cuadrupedia para glúteo medio. Apertura lateral de cadera con rodilla flexionada.',
    steps: [
      'Ponerse en cuadrupedia con las manos bajo los hombros',
      'Mantener la rodilla flexionada a 90 grados',
      'Abrir la pierna hacia el costado elevando la rodilla',
      'Mantener el torso estable sin rotar la cadera',
      'Bajar controladamente y repetir',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'abduccion-cuerpo',
    name: 'Abducción de Cadera Lateral',
    muscleGroup: 'piernas',
    description: 'Abducción de cadera acostado de lado. Ejercicio sin equipamiento para glúteo medio.',
    steps: [
      'Acostarse de lado con las piernas extendidas',
      'Apoyar la cabeza en el brazo inferior',
      'Elevar la pierna superior manteniéndola recta',
      'Subir hasta sentir la contracción en el glúteo',
      'Bajar controladamente sin apoyar sobre la otra pierna',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'sentadilla-smith',
    name: 'Sentadilla en Smith',
    muscleGroup: 'piernas',
    description: 'Sentadilla guiada en máquina Smith. Permite mayor carga con estabilidad.',
    steps: [
      'Colocar la barra en los trapecios debajo de la guía Smith',
      'Posicionar los pies ligeramente adelante del cuerpo',
      'Desbloquear la barra y bajar flexionando rodillas y caderas',
      'Descender hasta que los muslos estén paralelos al suelo',
      'Empujar hacia arriba extendiendo las piernas',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'sentadilla-frontal',
    name: 'Sentadilla Frontal',
    muscleGroup: 'piernas',
    description: 'Sentadilla con barra al frente. Mayor énfasis en cuádriceps y core.',
    steps: [
      'Colocar la barra sobre los deltoides anteriores con agarre cruzado o limpio',
      'Mantener los codos altos y el torso erguido',
      'Descender flexionando rodillas y caderas',
      'Bajar hasta que los muslos estén paralelos al suelo o más',
      'Empujar hacia arriba manteniendo los codos elevados',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'curl-femoral-pie',
    name: 'Curl Femoral de Pie',
    muscleGroup: 'piernas',
    description: 'Curl de isquiotibiales en posición de pie. Trabajo unilateral.',
    steps: [
      'Pararse con una pierna apoyada y la otra libre',
      'Flexionar la rodilla de la pierna libre llevando el talón al glúteo',
      'Contraer los isquiotibiales en la parte superior',
      'Bajar controladamente la pierna',
      'Completar las repeticiones y cambiar de pierna',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'peso-muerto-sumo',
    name: 'Peso Muerto Sumo',
    muscleGroup: 'piernas',
    description: 'Variante del peso muerto con postura amplia. Mayor trabajo de aductores y glúteos.',
    steps: [
      'Pararse con los pies más anchos que los hombros, puntas hacia afuera',
      'Agarrar la barra con agarre estrecho entre las piernas',
      'Mantener el pecho alto y la espalda recta',
      'Empujar el suelo con los pies extendiendo caderas y rodillas',
      'Bloquear arriba apretando glúteos y volver a bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'zancadas-caminando',
    name: 'Zancadas Caminando',
    muscleGroup: 'piernas',
    description: 'Zancadas en desplazamiento. Excelente para glúteos, cuádriceps y coordinación.',
    steps: [
      'Pararse con los pies juntos sosteniendo mancuernas o barra',
      'Dar un paso largo hacia adelante flexionando ambas rodillas',
      'Bajar hasta que la rodilla trasera casi toque el suelo',
      'Empujar con la pierna delantera y traer la trasera hacia adelante',
      'Continuar caminando alternando piernas',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'hip-thrust-barbell',
    name: 'Hip Thrust con Barra',
    muscleGroup: 'piernas',
    description: 'Variante del hip thrust con barra. Máxima activación de glúteos según estudios NSCA.',
    steps: [
      'Sentarse en el suelo con la espalda alta apoyada en un banco',
      'Colocar la barra sobre la cadera con almohadilla',
      'Apoyar los pies a la anchura de los hombros',
      'Empujar la cadera hacia arriba extendiendo completamente',
      'Apretar los glúteos arriba 1-2 segundos y bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'hip-thrust-banda',
    name: 'Hip Thrust con Banda',
    muscleGroup: 'piernas',
    description: 'Hip thrust con banda elástica. Ideal para casa o calentamiento de glúteos.',
    steps: [
      'Sentarse con la espalda apoyada en un banco o silla',
      'Colocar la banda elástica sobre las caderas y bajo las rodillas',
      'Apoyar los pies a la anchura de los hombros',
      'Elevar la cadera empujando contra la banda',
      'Apretar glúteos arriba y bajar controladamente',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'peso-muerto-mancuerna',
    name: 'Peso Muerto con Mancuernas',
    muscleGroup: 'piernas',
    description: 'Peso muerto usando mancuernas. Más accesible y permite ajustar el agarre fácilmente.',
    steps: [
      'Pararse con los pies al ancho de los hombros sosteniendo mancuernas',
      'Mantener la espalda recta y el pecho alto',
      'Bajar las mancuernas por delante de las piernas flexionando la cadera',
      'Sentir el estiramiento en los isquiotibiales',
      'Subir extendiendo la cadera y apretando los glúteos arriba',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'elevacion-cadera-banco',
    name: 'Elevación de Cadera en Banco',
    muscleGroup: 'piernas',
    description: 'Puente de glúteos con los pies elevados en un banco. Mayor rango de movimiento.',
    steps: [
      'Acostarse boca arriba con los pies apoyados en un banco',
      'Brazos a los costados con palmas hacia abajo',
      'Elevar la cadera empujando con los talones',
      'Apretar los glúteos en la posición superior',
      'Bajar controladamente sin apoyar completamente la cadera',
    ],
    videoUrl: 'SEARCH',
  },
  // ABDOMEN (casa - sin maquinas)
  {
    id: 'crunch-bicicleta',
    name: 'Crunch Bicicleta',
    muscleGroup: 'abdomen',
    description: 'Crunch rotatorio para oblicuos y recto abdominal.',
    steps: [
      'Acostarse boca arriba con manos detras de la cabeza',
      'Elevar las piernas con rodillas a 90 grados',
      'Llevar el codo derecho a la rodilla izquierda rotando el torso',
      'Alternar de forma continua como pedaleando',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    muscleGroup: 'abdomen',
    description: 'Ejercicio de estabilidad para core profundo.',
    steps: [
      'Acostarse boca arriba, brazos extendidos al techo, rodillas a 90 grados',
      'Extender brazo derecho atras y pierna izquierda al frente simultaneamente',
      'Mantener la espalda baja pegada al suelo',
      'Volver al centro y alternar',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    muscleGroup: 'abdomen',
    description: 'Ejercicio isometrico avanzado de gimnasia para todo el core.',
    steps: [
      'Acostarse boca arriba con brazos extendidos sobre la cabeza',
      'Elevar piernas y hombros del suelo',
      'Mantener la espalda baja pegada al suelo formando una C',
      'Mantener la posicion el tiempo indicado',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    muscleGroup: 'abdomen',
    description: 'Rotacion del torso para oblicuos. Se puede hacer con o sin peso.',
    steps: [
      'Sentarse con las rodillas flexionadas y pies ligeramente elevados',
      'Inclinar el torso hacia atras a 45 grados',
      'Rotar el torso de lado a lado tocando el suelo con las manos',
      'Mantener el core activado durante todo el movimiento',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'v-up',
    name: 'V-Up',
    muscleGroup: 'abdomen',
    description: 'Crunch avanzado elevando piernas y torso simultaneamente.',
    steps: [
      'Acostarse boca arriba con brazos extendidos sobre la cabeza',
      'Elevar piernas y torso simultaneamente formando una V',
      'Intentar tocar los pies con las manos',
      'Bajar controladamente al suelo',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'plancha-lateral',
    name: 'Plancha Lateral',
    muscleGroup: 'abdomen',
    description: 'Ejercicio isometrico para oblicuos y estabilidad lateral.',
    steps: [
      'Apoyar un antebrazo y el lateral del pie en el suelo',
      'Elevar las caderas formando una linea recta de cabeza a pies',
      'Mantener el core activado',
      'Mantener la posicion el tiempo indicado',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'crunch-suelo',
    name: 'Crunch en Suelo',
    muscleGroup: 'abdomen',
    description: 'Crunch basico en suelo para recto abdominal.',
    steps: [
      'Acostarse boca arriba con rodillas flexionadas',
      'Manos detras de la cabeza sin tirar del cuello',
      'Elevar los hombros del suelo contrayendo el abdomen',
      'Bajar controladamente sin apoyar completamente',
    ],
    videoUrl: 'SEARCH',
  },
  // CARDIO
  {
    id: 'hiit-cinta',
    name: 'HIIT en Cinta',
    muscleGroup: 'cardio',
    description: 'Intervalos de alta intensidad para quemar grasa.',
    steps: [
      'Calentar 3 minutos caminando rápido',
      'Sprint 30 segundos a máxima intensidad',
      'Descanso activo 60 segundos caminando',
      'Repetir el ciclo 8-12 veces',
      'Enfriar 3 minutos caminando suave',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'saltar-cuerda',
    name: 'Saltar la Cuerda',
    muscleGroup: 'cardio',
    description: 'Ejercicio cardiovascular completo y accesible.',
    steps: [
      'De pie con la cuerda detrás de los pies',
      'Girar la cuerda con las muñecas, no con los brazos',
      'Saltar lo justo para que pase la cuerda',
      'Mantener el core activado',
      'Aterrizar suavemente sobre la parte delantera de los pies',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'burpees',
    name: 'Burpees',
    muscleGroup: 'cardio',
    description: 'Ejercicio de cuerpo completo y cardio de alta intensidad.',
    steps: [
      'De pie, bajar a posicion de sentadilla con manos en el suelo',
      'Saltar los pies hacia atras a posicion de flexion',
      'Hacer una flexion',
      'Saltar los pies hacia las manos',
      'Saltar hacia arriba con los brazos extendidos',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    muscleGroup: 'cardio',
    description: 'Ejercicio cardio clasico sin equipamiento.',
    steps: [
      'De pie con los pies juntos y brazos a los lados',
      'Saltar abriendo piernas y elevando brazos sobre la cabeza',
      'Saltar volviendo a la posicion inicial',
      'Mantener un ritmo constante',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'high-knees',
    name: 'Rodillas Altas',
    muscleGroup: 'cardio',
    description: 'Correr en el lugar elevando las rodillas al pecho.',
    steps: [
      'De pie, correr en el lugar',
      'Elevar las rodillas lo mas alto posible, al nivel de la cadera',
      'Mantener el core activado y la espalda recta',
      'Bombear los brazos como al correr',
    ],
    videoUrl: 'SEARCH',
  },
  {
    id: 'hiit-casa',
    name: 'HIIT en Casa',
    muscleGroup: 'cardio',
    description: 'Circuito HIIT de alta intensidad sin equipamiento.',
    steps: [
      'Calentar 2 minutos con jumping jacks suaves',
      '30 segundos de burpees a maxima intensidad',
      '30 segundos de descanso activo',
      '30 segundos de rodillas altas a maxima intensidad',
      'Repetir el circuito 6-10 veces',
    ],
    videoUrl: 'SEARCH',
  },
  // ============ NUEVOS EJERCICIOS (GYM) ============
  // PECHO
  { id: 'press-mancuernas-plano', name: 'Press Mancuernas Plano', muscleGroup: 'pecho',
    description: 'Press de pecho con mancuernas en banco plano. Mayor rango de movimiento que con barra.',
    steps: ['Acostarse en banco plano con una mancuerna en cada mano', 'Empujar las mancuernas hacia arriba hasta extender los brazos', 'Bajar controladamente hasta que los codos formen 90 grados', 'Mantener los pies firmes en el suelo'], videoUrl: 'SEARCH' },
  { id: 'press-mancuernas-inclinado', name: 'Press Mancuernas Inclinado', muscleGroup: 'pecho',
    description: 'Press con mancuernas en banco inclinado para pecho superior.',
    steps: ['Ajustar banco a 30-45 grados', 'Empujar mancuernas hacia arriba', 'Bajar controladamente a la altura del pecho', 'No bloquear los codos arriba'], videoUrl: 'SEARCH' },
  { id: 'apertura-mancuerna-plano', name: 'Apertura Mancuerna Plano', muscleGroup: 'pecho',
    description: 'Aperturas con mancuernas en banco plano para aislar el pectoral.',
    steps: ['Acostarse en banco plano con mancuernas sobre el pecho', 'Abrir los brazos en arco hacia los lados', 'Mantener ligera flexion en los codos', 'Volver apretando el pecho'], videoUrl: 'SEARCH' },
  // ESPALDA
  { id: 'remo-t', name: 'Remo en T', muscleGroup: 'espalda',
    description: 'Remo con barra T para grosor de espalda media.',
    steps: ['Colocarse sobre la barra T con agarre cerrado', 'Inclinar el torso a 45 grados', 'Tirar la barra hacia el abdomen', 'Apretar omoplatos arriba y bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'pullover-mancuerna', name: 'Pullover con Mancuerna', muscleGroup: 'espalda',
    description: 'Ejercicio clasico para dorsales y serrato anterior.',
    steps: ['Acostarse en banco con solo hombros apoyados', 'Sostener mancuerna con ambas manos sobre el pecho', 'Bajar detras de la cabeza con brazos semi-extendidos', 'Volver apretando dorsales'], videoUrl: 'SEARCH' },
  { id: 'remo-posterior-cable', name: 'Remo Posterior en Cable', muscleGroup: 'espalda',
    description: 'Remo con cable para deltoides posterior y espalda alta.',
    steps: ['De pie frente a polea alta con cuerda', 'Tirar hacia la cara separando las manos', 'Rotar hombros hacia atras', 'Volver controladamente'], videoUrl: 'SEARCH' },
  // HOMBROS
  { id: 'elevacion-posterior', name: 'Elevacion Posterior con Barra', muscleGroup: 'hombros',
    description: 'Ejercicio para deltoides posterior con barra.',
    steps: ['Inclinar torso a 90 grados con barra colgando', 'Elevar la barra hacia los lados', 'Mantener ligera flexion en codos', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'elevacion-posterior-mancuerna', name: 'Elevacion Posterior Mancuerna', muscleGroup: 'hombros',
    description: 'Pajaro con mancuernas para deltoides posterior.',
    steps: ['Inclinar torso a 90 grados con mancuernas', 'Elevar mancuernas hacia los lados', 'Apretar omoplatos arriba', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'elevacion-lateral-cable', name: 'Elevacion Lateral en Cable', muscleGroup: 'hombros',
    description: 'Elevacion lateral con cable para tension constante en deltoides.',
    steps: ['De pie al lado de la polea baja', 'Agarrar la manija con la mano lejana', 'Elevar el brazo hasta la altura del hombro', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'encogimientos-trapecio', name: 'Encogimientos de Trapecio', muscleGroup: 'hombros',
    description: 'Encogimientos con mancuernas para trapecio superior.',
    steps: ['De pie con mancuernas a los lados', 'Elevar los hombros hacia las orejas', 'Mantener arriba 1-2 segundos', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  // BICEPS
  { id: 'curl-cable', name: 'Curl en Cable', muscleGroup: 'biceps',
    description: 'Curl de biceps con cable para tension constante.',
    steps: ['De pie frente a polea baja con barra recta', 'Flexionar codos subiendo la barra', 'Mantener codos pegados al cuerpo', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'curl-inclinado-martillo', name: 'Curl Inclinado Martillo', muscleGroup: 'biceps',
    description: 'Curl martillo en banco inclinado para mayor estiramiento del biceps.',
    steps: ['Sentarse en banco inclinado a 45 grados', 'Mancuernas colgando con agarre neutro', 'Flexionar codos sin rotar munecas', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'curl-reverso', name: 'Curl Reverso con Barra', muscleGroup: 'biceps',
    description: 'Curl con agarre prono para braquiorradial y antebrazo.',
    steps: ['De pie con barra agarre prono', 'Flexionar codos subiendo la barra', 'Mantener codos fijos', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  // TRICEPS
  { id: 'extension-triceps-overhead', name: 'Extension Triceps Overhead', muscleGroup: 'triceps',
    description: 'Extension de triceps sobre la cabeza con barra o mancuerna.',
    steps: ['Sentado o de pie con barra/mancuerna sobre la cabeza', 'Flexionar codos bajando el peso detras de la cabeza', 'Extender brazos volviendo arriba', 'Mantener codos apuntando al frente'], videoUrl: 'SEARCH' },
  { id: 'fondos-paralelas', name: 'Fondos en Paralelas', muscleGroup: 'triceps',
    description: 'Fondos en barras paralelas para triceps y pecho inferior.',
    steps: ['Apoyar manos en las barras paralelas', 'Bajar el cuerpo flexionando codos a 90 grados', 'Inclinarse levemente hacia adelante para pecho', 'Empujar hacia arriba hasta extender brazos'], videoUrl: 'SEARCH' },
  // PIERNAS
  { id: 'hack-squat', name: 'Hack Squat', muscleGroup: 'piernas',
    description: 'Sentadilla en maquina hack para cuadriceps.',
    steps: ['Colocarse en la maquina con espalda apoyada', 'Pies a la anchura de los hombros en la plataforma', 'Bajar flexionando rodillas a 90 grados', 'Empujar hacia arriba sin bloquear rodillas'], videoUrl: 'SEARCH' },
  { id: 'peso-muerto-rumano', name: 'Peso Muerto Rumano', muscleGroup: 'piernas',
    description: 'Variante del peso muerto que enfatiza isquiotibiales y gluteos.',
    steps: ['De pie con barra a la altura de las caderas', 'Bajar la barra deslizandola por las piernas', 'Mantener piernas casi rectas con leve flexion', 'Subir empujando caderas hacia adelante'], videoUrl: 'SEARCH' },
  { id: 'sentadilla-goblet', name: 'Sentadilla Goblet', muscleGroup: 'piernas',
    description: 'Sentadilla sosteniendo una mancuerna o kettlebell al pecho.',
    steps: ['Sostener mancuerna vertical contra el pecho', 'Bajar a posicion de sentadilla profunda', 'Mantener el torso erguido y codos adentro', 'Subir empujando con los talones'], videoUrl: 'SEARCH' },
  { id: 'buenos-dias', name: 'Buenos Dias', muscleGroup: 'piernas',
    description: 'Ejercicio para isquiotibiales y cadena posterior con barra.',
    steps: ['Barra sobre los trapecios como en sentadilla', 'Inclinar el torso hacia adelante con piernas casi rectas', 'Bajar hasta que el torso este paralelo al suelo', 'Subir apretando gluteos e isquiotibiales'], videoUrl: 'SEARCH' },
  { id: 'pantorrilla-sentado', name: 'Elevacion Pantorrilla Sentado', muscleGroup: 'piernas',
    description: 'Ejercicio para soleo (pantorrilla) en posicion sentada.',
    steps: ['Sentarse en la maquina con rodillas bajo la almohadilla', 'Subir en puntas de pie apretando pantorrillas', 'Mantener arriba 1-2 segundos', 'Bajar controladamente estirando'], videoUrl: 'SEARCH' },
  // ABDOMEN
  { id: 'rueda-abdominal', name: 'Rueda Abdominal', muscleGroup: 'abdomen',
    description: 'Ejercicio avanzado con rueda ab para core completo.',
    steps: ['Arrodillarse con la rueda frente a vos', 'Rodar la rueda hacia adelante extendiendo el cuerpo', 'Mantener el core activado sin arquear la espalda', 'Volver a la posicion inicial controladamente'], videoUrl: 'SEARCH' },
  // ============ EJERCICIOS UNILATERALES ============
  { id: 'remo-cable-unilateral', name: 'Remo Unilateral en Cable', muscleGroup: 'espalda',
    description: 'Remo con un brazo en cable para corregir desbalances de espalda.',
    steps: ['De pie frente a polea baja con una mano', 'Tirar hacia la cadera manteniendo el codo cerca del cuerpo', 'Apretar el dorsal en la contraccion', 'Bajar controladamente y repetir'], videoUrl: 'SEARCH' },
  { id: 'remo-barra-unilateral', name: 'Remo Unilateral con Barra', muscleGroup: 'espalda',
    description: 'Remo con un extremo de la barra para trabajo unilateral de espalda.',
    steps: ['Agarrar un extremo de la barra con una mano', 'Inclinar torso a 45 grados', 'Tirar la barra hacia la cadera', 'Bajar controladamente'], videoUrl: 'SEARCH' },
  { id: 'peso-muerto-unilateral', name: 'Peso Muerto a Una Pierna', muscleGroup: 'piernas',
    description: 'Peso muerto unilateral para gluteos, isquiotibiales y equilibrio.',
    steps: ['De pie sobre una pierna con mancuerna en la mano opuesta', 'Inclinar torso hacia adelante extendiendo la pierna libre atras', 'Mantener la espalda recta', 'Volver a la posicion inicial'], videoUrl: 'SEARCH' },
  { id: 'split-squat-mancuerna', name: 'Split Squat con Mancuerna', muscleGroup: 'piernas',
    description: 'Sentadilla dividida con mancuernas para trabajo unilateral de piernas.',
    steps: ['De pie con un pie adelante y otro atras, mancuernas a los lados', 'Bajar la rodilla trasera hacia el suelo', 'La rodilla delantera no pasa la punta del pie', 'Subir empujando con el pie delantero'], videoUrl: 'SEARCH' },
  { id: 'sentadilla-unilateral', name: 'Sentadilla a Una Pierna con Mancuerna', muscleGroup: 'piernas',
    description: 'Sentadilla unilateral con mancuerna para fuerza y equilibrio.',
    steps: ['De pie sobre una pierna con mancuerna en el pecho', 'Bajar controladamente en una pierna', 'Mantener la otra pierna extendida al frente', 'Subir empujando con el talon'], videoUrl: 'SEARCH' },
  { id: 'pantorrilla-unilateral', name: 'Pantorrilla a Una Pierna', muscleGroup: 'piernas',
    description: 'Elevacion de pantorrilla unilateral para corregir desbalances.',
    steps: ['De pie sobre un escalon con un pie', 'Subir en punta de pie apretando la pantorrilla', 'Mantener arriba 2 segundos', 'Bajar estirando la pantorrilla'], videoUrl: 'SEARCH' },
  // KITESURF - CORE / ANTI-ROTACION
  { id: 'pallof-press', name: 'Pallof Press', muscleGroup: 'abdomen',
    description: 'Ejercicio anti-rotación con cable o banda. Fortalece el core para resistir fuerzas rotacionales.',
    steps: ['Colocarse de lado a la polea con el cable a la altura del pecho', 'Agarrar el mango con ambas manos frente al esternón', 'Extender los brazos al frente manteniendo el torso recto', 'Resistir la rotación que genera el cable', 'Sostener 2 segundos con los brazos extendidos y volver controlado'], videoUrl: 'SEARCH' },
  { id: 'bird-dog', name: 'Bird Dog', muscleGroup: 'abdomen',
    description: 'Ejercicio de estabilidad contralateral. Mejora la coordinación y equilibrio del core.',
    steps: ['Colocarse en posición de cuatro puntos', 'Extender brazo derecho y pierna izquierda simultáneamente', 'Mantener la espalda completamente recta', 'Sostener 2-3 segundos con el core activado', 'Volver controlado y repetir con el lado opuesto'], videoUrl: 'SEARCH' },
  { id: 'stir-the-pot', name: 'Stir the Pot', muscleGroup: 'abdomen',
    description: 'Plancha dinámica sobre pelota suiza. Máxima activación del core con anti-rotación.',
    steps: ['Apoyar antebrazos sobre pelota suiza en posición de plancha', 'Mantener cuerpo recto, core activado', 'Hacer pequeños círculos con los antebrazos', 'Resistir la rotación del torso', 'Realizar 8-10 círculos en cada dirección'], videoUrl: 'SEARCH' },
  { id: 'woodchop-polea', name: 'Wood Chop en Polea', muscleGroup: 'abdomen',
    description: 'Movimiento rotacional con cable. Desarrolla potencia rotacional.',
    steps: ['Colocarse de lado a la polea con cable en posición alta', 'Agarrar el mango con ambas manos', 'Rotar el torso tirando en diagonal de arriba hacia abajo', 'Los pies giran acompañando la rotación', 'Volver controlado a la posición inicial'], videoUrl: 'SEARCH' },
  // KITESURF - GRIP / AGARRE
  { id: 'dead-hang', name: 'Dead Hang', muscleGroup: 'espalda',
    description: 'Colgarse pasivamente de la barra. Fortalece el agarre y descomprime la columna.',
    steps: ['Agarrar la barra con ambas manos en pronación', 'Colgarse con brazos extendidos', 'Activar ligeramente los hombros', 'Mantener el máximo tiempo posible', 'Respirar de forma controlada'], videoUrl: 'SEARCH' },
  { id: 'farmer-walk', name: 'Farmer Walk', muscleGroup: 'espalda',
    description: 'Caminata con peso. Fortalece agarre, core y estabilidad general.',
    steps: ['Agarrar una mancuerna pesada en cada mano', 'Mantener postura erguida', 'Caminar con pasos controlados', 'No dejar que el peso incline el cuerpo', 'Recorrer 20-30 metros por serie'], videoUrl: 'SEARCH' },
  { id: 'towel-pull-up', name: 'Dominadas con Toalla', muscleGroup: 'espalda',
    description: 'Dominadas agarrando una toalla. Intensifica el trabajo de agarre.',
    steps: ['Colgar dos toallas sobre la barra', 'Agarrar una toalla con cada mano', 'Realizar una dominada traccionando con la espalda', 'El agarre inestable fuerza los antebrazos', 'Bajar controlado y repetir'], videoUrl: 'SEARCH' },
  // KITESURF - FUNCIONAL / ROTACIONAL
  { id: 'turkish-getup', name: 'Turkish Get-Up', muscleGroup: 'abdomen',
    description: 'Levantada turca completa. Cuerpo completo para estabilidad y fuerza funcional.',
    steps: ['Acostarse boca arriba con pesa en brazo derecho extendido', 'Flexionar rodilla derecha con pie apoyado', 'Levantarse progresivamente: codo, mano, cadera, rodilla, de pie', 'Mantener brazo extendido durante todo el movimiento', 'Invertir el movimiento para volver al suelo'], videoUrl: 'SEARCH' },
  { id: 'renegade-row', name: 'Renegade Row', muscleGroup: 'espalda',
    description: 'Remo en posición de plancha con mancuernas. Anti-rotación con tracción.',
    steps: ['Posición de plancha con manos sobre mancuernas', 'Core completamente activado', 'Remar una mancuerna hacia la cadera sin rotar', 'Bajar controlado y repetir con el otro brazo', 'Separar pies para mayor estabilidad'], videoUrl: 'SEARCH' },
  { id: 'landmine-press', name: 'Landmine Press', muscleGroup: 'hombros',
    description: 'Press con barra en mina. Hombro unilateral con patrón angular seguro.',
    steps: ['Colocar extremo de barra en esquina o soporte', 'Agarrar extremo libre con una mano al hombro', 'Empujar la barra hacia arriba y al frente', 'Movimiento angular más seguro para el hombro', 'Bajar controlado hasta el hombro'], videoUrl: 'SEARCH' },
  // KITESURF - BALANCE / UNILATERAL
  { id: 'single-leg-rdl', name: 'Peso Muerto Rumano a Una Pierna', muscleGroup: 'piernas',
    description: 'Peso muerto rumano unilateral. Mejora equilibrio y fuerza de isquiotibiales.',
    steps: ['Pararse sobre una pierna con rodilla ligeramente flexionada', 'Mancuerna en mano opuesta a pierna de apoyo', 'Inclinar torso hacia adelante extendiendo pierna libre', 'Bajar mancuerna manteniendo espalda recta', 'Volver activando glúteo e isquiotibial'], videoUrl: 'SEARCH' },
  { id: 'bosu-squat', name: 'Sentadilla en Bosu', muscleGroup: 'piernas',
    description: 'Sentadilla sobre superficie inestable. Mejora propiocepción y estabilidad.',
    steps: ['Pararse sobre bosu con parte plana hacia arriba', 'Pies al ancho de hombros, buscar equilibrio', 'Sentadilla controlada manteniendo equilibrio', 'Bajar hasta donde se pueda sin perder postura', 'Subir activando cuádriceps y glúteos'], videoUrl: 'SEARCH' },
  // KITESURF - PREVENCION DE LESIONES
  { id: 'band-pull-apart', name: 'Band Pull Apart', muscleGroup: 'hombros',
    description: 'Separación de banda elástica. Deltoides posterior y manguito rotador.',
    steps: ['Banda elástica con ambas manos frente al pecho', 'Separar las manos estirando la banda', 'Apretar omóplatos juntos al final', 'Volver controlado sin rebote', 'Mantener brazos a altura de hombros'], videoUrl: 'SEARCH' },
  { id: 'external-rotation', name: 'Rotación Externa con Banda', muscleGroup: 'hombros',
    description: 'Rotación externa del hombro. Esencial para el manguito rotador.',
    steps: ['Banda o cable a la altura del codo', 'Codo a 90 grados pegado al costado', 'Rotar antebrazo hacia afuera', 'Controlar movimiento al abrir y cerrar', 'Realizar 15-20 reps con resistencia ligera'], videoUrl: 'SEARCH' },
];

export function getVideoUrl(exercise: Exercise): string {
  if (exercise.videoUrl && exercise.videoUrl !== 'SEARCH') {
    return exercise.videoUrl;
  }
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(exercise.name + ' tecnica correcta ejercicio gym')}`;
}
export function getExercisesByMuscleGroup(muscleGroup: string): Exercise[] {
  return EXERCISES.filter(e => e.muscleGroup === muscleGroup);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id);
}

export const MUSCLE_GROUP_LABELS: Record<string, string> = {
  pecho: 'Pecho',
  espalda: 'Espalda',
  hombros: 'Hombros',
  biceps: 'Bíceps',
  triceps: 'Tríceps',
  piernas: 'Piernas',
  abdomen: 'Abdomen',
  cardio: 'Cardio',
};
