import type { Plan } from '@/types';

export const PLANS: Plan[] = [
  {
    id: '1',
    slug: 'quema-grasa',
    name: 'Quema Grasa',
    shortDescription: 'Pierde grasa corporal de forma efectiva y sostenible',
    description: 'Plan diseñado para maximizar la pérdida de grasa corporal mediante un déficit calórico controlado, combinando entrenamiento HIIT con trabajo de pesas para preservar masa muscular.',
    includes: [
      'Plan de entrenamiento HIIT + pesas personalizado',
      'Plan de nutrición con déficit calórico controlado',
      'Cálculo de macros personalizado',
      'Seguimiento semanal de progreso',
      'Videos explicativos de cada ejercicio',
      'Ajustes mensuales según progreso',
    ],
    icon: 'Flame',
    color: '#FF4444',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '2',
    slug: 'ganancia-muscular',
    name: 'Ganancia Muscular',
    shortDescription: 'Aumenta tu masa muscular con un plan progresivo',
    description: 'Plan de hipertrofia progresiva con superávit calórico controlado. Ideal para quienes buscan ganar volumen muscular de forma limpia.',
    includes: [
      'Rutina de hipertrofia progresiva (4-5 días/semana)',
      'Plan nutricional con superávit calórico',
      'Suplementación recomendada',
      'Seguimiento de progreso con fotos y medidas',
      'Videos de técnica de cada ejercicio',
      'Progresión de cargas mensual',
    ],
    icon: 'Dumbbell',
    color: '#4CAF50',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '3',
    slug: 'tonificacion',
    name: 'Tonificación',
    shortDescription: 'Define tu cuerpo sin ganar volumen excesivo',
    description: 'Plan equilibrado que combina circuitos con pesas moderadas y una dieta normocalórica para definir tu cuerpo.',
    includes: [
      'Circuitos de entrenamiento + pesas moderadas',
      'Plan nutricional equilibrado',
      'Rutinas variadas para evitar estancamiento',
      'Seguimiento semanal',
      'Videos de todos los ejercicios',
      'Tips de recuperación y descanso',
    ],
    icon: 'Sparkles',
    color: '#FF9800',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '4',
    slug: 'principiante-total',
    name: 'Principiante Total',
    shortDescription: 'Tu primer paso hacia una vida fitness',
    description: 'Plan diseñado para personas que nunca entrenaron. Incluye educación nutricional y ejercicios básicos con progresión gradual.',
    includes: [
      'Ejercicios básicos con progresión gradual',
      'Educación nutricional paso a paso',
      'Guía de uso de equipamiento del gym',
      'Videos detallados de cada ejercicio',
      'Acompañamiento personalizado',
      'Plan de 3 días/semana progresivo',
    ],
    icon: 'GraduationCap',
    color: '#2196F3',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '5',
    slug: 'rendimiento-deportivo',
    name: 'Rendimiento Deportivo',
    shortDescription: 'Mejora tu rendimiento en tu deporte',
    description: 'Plan de periodización deportiva con nutrición enfocada en timing. Ideal para corredores, futbolistas, ciclistas y otros deportistas.',
    includes: [
      'Periodización según tu deporte',
      'Nutrición con timing pre/intra/post entrenamiento',
      'Plan de prevención de lesiones',
      'Seguimiento de métricas de rendimiento',
      'Videos de ejercicios específicos',
      'Ajustes según calendario deportivo',
    ],
    icon: 'Trophy',
    color: '#9C27B0',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '6',
    slug: 'post-parto',
    name: 'Post-Parto',
    shortDescription: 'Recupera tu cuerpo después del embarazo',
    description: 'Plan de recuperación progresiva post embarazo con nutrición adaptada a la lactancia. Seguro y efectivo.',
    includes: [
      'Recuperación progresiva del core',
      'Nutrición adaptada a lactancia',
      'Ejercicios seguros post-parto',
      'Progresión personalizada según recuperación',
      'Videos con técnica detallada',
      'Acompañamiento sensible y profesional',
    ],
    icon: 'Heart',
    color: '#E91E63',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '7',
    slug: 'fuerza-funcional',
    name: 'Fuerza Funcional',
    shortDescription: 'Fuerza real para tu vida diaria',
    description: 'Enfocado en movimientos compuestos y movilidad. Ideal para adultos +40 o personas con trabajos sedentarios.',
    includes: [
      'Movimientos compuestos funcionales',
      'Trabajo de movilidad y flexibilidad',
      'Nutrición para mantenimiento y energía',
      'Prevención de dolores posturales',
      'Videos de técnica correcta',
      'Rutinas adaptables en casa o gym',
    ],
    icon: 'Shield',
    color: '#607D8B',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '8',
    slug: 'recomposicion-corporal',
    name: 'Recomposición Corporal',
    shortDescription: 'Pierde grasa y gana músculo a la vez',
    description: 'Plan para perder grasa y ganar músculo simultáneamente. Ideal para personas con peso normal pero poca masa muscular.',
    includes: [
      'Déficit calórico leve con alto proteínas',
      'Entrenamiento de hipertrofia optimizado',
      'Nutrición con cycling de carbohidratos',
      'Seguimiento de composición corporal',
      'Videos de todos los ejercicios',
      'Ajustes cada 4 semanas',
    ],
    icon: 'RefreshCw',
    color: '#00BCD4',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
  {
    id: '9',
    slug: 'plan-pareja',
    name: 'Plan Pareja',
    shortDescription: 'Entrenen juntos, crezcan juntos',
    description: 'Dos planes coordinados para entrenar en pareja con comidas compartidas. Motivación x2.',
    includes: [
      '2 planes de entrenamiento coordinados',
      'Plan de comidas compartido',
      'Rutinas para hacer juntos',
      'Seguimiento de progreso individual',
      'Videos de ejercicios en pareja',
      'Descuento especial vs planes individuales',
    ],
    icon: 'Users',
    color: '#FF5722',
    prices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
    isCouple: true,
  },
  {
    id: '10',
    slug: 'competicion',
    name: 'Competición',
    shortDescription: 'Prepárate para competir como profesional',
    description: 'Preparación completa para competencias de fitness y bodybuilding. Incluye periodización, peak week y posing.',
    includes: [
      'Periodización completa de competición',
      'Nutrición con peak week',
      'Rutinas de posing',
      'Preparación de agua y sodio',
      'Seguimiento diario pre-competencia',
      'Acompañamiento el día de la competencia',
    ],
    icon: 'Medal',
    color: '#FFD700',
    prices: { '1-mes': 3200, '3-meses': 7680, '6-meses': 12800, '1-ano': 19200 },
    couplePrices: { '1-mes': 5120, '3-meses': 12290, '6-meses': 20480, '1-ano': 30720 },
  },
];

export const DURATION_LABELS: Record<string, string> = {
  '1-mes': '1 Mes',
  '3-meses': '3 Meses',
  '6-meses': '6 Meses',
  '1-ano': '1 Año',
};

export const DURATION_DESCRIPTIONS: Record<string, string> = {
  '1-mes': 'Ideal para probar',
  '3-meses': 'Resultados visibles',
  '6-meses': 'Transformación real',
  '1-ano': 'Cambio de vida',
};

export function getPlanBySlug(slug: string): Plan | undefined {
  return PLANS.find(p => p.slug === slug);
}

export function formatPrice(price: number): string {
  return price.toLocaleString("es-UY");
}

export function getDiscountPercentage(duration: string): number {
  const discounts: Record<string, number> = {
    '1-mes': 0,
    '3-meses': 20,
    '6-meses': 33,
    '1-ano': 50,
  };
  return discounts[duration] ?? 0;
}
